const extraCss=document.createElement("link");extraCss.rel="stylesheet";extraCss.href="styles-extra.css";document.head.appendChild(extraCss);
const PHONE="38669843976";
const copy={
en:{home:"Home",services:"Services",resellers:"Resellers",installation:"Installation",contact:"Contact",eyebrow:"Premium entertainment, your way",watch:"Watch the world.",withoutLimits:"Without limits.",heroCopy:"Live television, movies and series from around the world — beautifully organized and ready on every screen.",explore:"Explore our services",freeTest:"Request a free test",premiumServices:"premium services",support:"customer support",quality:"picture quality",discover:"Discover",ourServices:"Our services",chooseExperience:"Choose your viewing experience.",servicesCopy:"Four carefully selected services. One simple goal: reliable entertainment, exactly how you want it.",orbitCopy:"Our flagship service with 3 simultaneous connections and a complete installation center.",lionCopy:"A smooth, reliable OTT experience with a complimentary 12-hour test.",megaCopy:"A flexible entertainment package with simple setup across popular devices.",strongCopy:"Premium performance, dedicated apps and broad device compatibility.",from:"From",specialOffer:"Special offer",twoYears:"Two years. One great price.",dealCopy:"Commit to more entertainment and save. Our best long-term value is available across all four services.",claim:"Claim this offer",business:"A BUSINESS OPPORTUNITY",grow:"Grow with Orbit IPTV.",resellerCopy:"Get your own reseller panel, create subscriptions in seconds and build recurring income.",resellerProgram:"View reseller program",backHome:"Back to Home",allServices:"All services",plans:"Simple, transparent plans",choosePlan:"Choose a subscription",planCopy:"No contract. Friendly support. Your entertainment starts within minutes.",order:"Order on WhatsApp",test:"Request free test",features:"What is included",live:"Live television",movies:"Movies & series",device:"Popular devices",help:"Friendly support",installTitle:"Installation center",installCopy:"Choose your service and device. These official apps and players make setup quick and simple.",open:"Open / download",resellerTitle:"Become an Orbit IPTV reseller",resellerLead:"Create subscriptions for your customers with your own panel. Free 24-hour test codes are available.",credits:"Credits + panel",join:"Join on WhatsApp",periods:"Subscription periods",hours:"24-hour test",included:"available free",connections:"connection",connections3:"3 connections"},
bs:{home:"Početna",services:"Usluge",resellers:"Preprodavači",installation:"Instalacija",contact:"Kontakt",eyebrow:"Premium zabava, po vašoj mjeri",watch:"Gledajte svijet.",withoutLimits:"Bez granica.",heroCopy:"Televizija uživo, filmovi i serije iz cijelog svijeta — uredno složeni i dostupni na svakom ekranu.",explore:"Pogledajte ponudu",freeTest:"Zatraži besplatan test",premiumServices:"premium usluge",support:"korisnička podrška",quality:"kvaliteta slike",discover:"Otkrijte",ourServices:"Naše usluge",chooseExperience:"Izaberite svoje TV iskustvo.",servicesCopy:"Četiri pažljivo odabrane usluge. Jedan cilj: pouzdana zabava baš po vašoj želji.",orbitCopy:"Naša glavna usluga s 3 istovremene konekcije i kompletnim instalacijskim centrom.",lionCopy:"Stabilno OTT iskustvo uz besplatan test od 12 sati.",megaCopy:"Fleksibilan paket zabave s jednostavnom instalacijom na popularnim uređajima.",strongCopy:"Premium performanse, posebne aplikacije i široka podrška za uređaje.",from:"Od",specialOffer:"Posebna ponuda",twoYears:"Dvije godine. Jedna odlična cijena.",dealCopy:"Više zabave uz veću uštedu. Najbolja dugoročna ponuda za sve četiri usluge.",claim:"Zatraži ponudu",business:"POSLOVNA PRILIKA",grow:"Rastite uz Orbit IPTV.",resellerCopy:"Dobijte svoj panel, kreirajte pretplate za nekoliko sekundi i razvijajte stalnu zaradu.",resellerProgram:"Program za preprodavače",backHome:"Nazad na početnu",allServices:"Sve usluge",plans:"Jednostavne i jasne cijene",choosePlan:"Izaberite pretplatu",planCopy:"Bez ugovora. Ljubazna podrška. Zabava počinje za nekoliko minuta.",order:"Naruči na WhatsApp",test:"Zatraži besplatan test",features:"Šta je uključeno",live:"TV uživo",movies:"Filmovi i serije",device:"Popularni uređaji",help:"Ljubazna podrška",installTitle:"Centar za instalaciju",installCopy:"Izaberite uslugu i uređaj. Službene aplikacije i playeri omogućavaju brzo podešavanje.",open:"Otvori / preuzmi",resellerTitle:"Postanite Orbit IPTV preprodavač",resellerLead:"Kreirajte pretplate za svoje klijente preko vlastitog panela. Besplatni test kodovi od 24 sata su dostupni.",credits:"Krediti + panel",join:"Prijavi se na WhatsApp",periods:"Trajanje pretplate",hours:"24-satni test",included:"dostupan besplatno",connections:"konekcija",connections3:"3 konekcije"}
};
copy.de={...copy.en,home:"Start",services:"Dienste",resellers:"Wiederverkäufer",installation:"Installation",contact:"Kontakt",freeTest:"Kostenlosen Test anfordern",backHome:"Zurück zur Startseite",order:"Auf WhatsApp bestellen",test:"Kostenlosen Test anfordern"};
copy.sl={...copy.en,home:"Domov",services:"Storitve",resellers:"Prodajalci",installation:"Namestitev",contact:"Kontakt",freeTest:"Zahtevajte brezplačni test",backHome:"Nazaj domov",order:"Naroči prek WhatsAppa",test:"Brezplačni test"};
copy.it={...copy.en,home:"Home",services:"Servizi",resellers:"Rivenditori",installation:"Installazione",contact:"Contatti",freeTest:"Richiedi una prova gratuita",backHome:"Torna alla Home",order:"Ordina su WhatsApp",test:"Prova gratuita"};
copy.sq={...copy.en,home:"Kryefaqja",services:"Shërbimet",resellers:"Rishitësit",installation:"Instalimi",contact:"Kontakti",eyebrow:"Argëtim premium, sipas dëshirës suaj",watch:"Shikoni botën.",withoutLimits:"Pa kufij.",explore:"Shiko shërbimet",freeTest:"Kërko test falas",ourServices:"Shërbimet tona",chooseExperience:"Zgjidhni përvojën tuaj televizive.",from:"Nga",specialOffer:"Ofertë speciale",claim:"Merr ofertën",backHome:"Kthehu në kryefaqe",allServices:"Të gjitha shërbimet",choosePlan:"Zgjidhni abonimin",order:"Porosit në WhatsApp",test:"Kërko test falas",installation:"Instalimi",join:"Bashkohu në WhatsApp"};
copy.sr={...copy.bs,home:"Početna",services:"Usluge",resellers:"Preprodavci",installation:"Instalacija",contact:"Kontakt",freeTest:"Zatraži besplatan test",backHome:"Nazad na početnu",order:"Naruči na WhatsApp"};
copy.hr={...copy.bs,home:"Početna",services:"Usluge",resellers:"Preprodavači",installation:"Instalacija",contact:"Kontakt",freeTest:"Zatraži besplatni test",backHome:"Natrag na početnu",order:"Naruči putem WhatsAppa"};
copy.mk={...copy.en,home:"Почетна",services:"Услуги",resellers:"Препродавачи",installation:"Инсталација",contact:"Контакт",watch:"Гледајте го светот.",withoutLimits:"Без граници.",explore:"Погледнете ги услугите",freeTest:"Побарајте бесплатен тест",ourServices:"Нашите услуги",from:"Од",specialOffer:"Специјална понуда",backHome:"Назад на почетна",choosePlan:"Изберете претплата",order:"Нарачајте преку WhatsApp",test:"Бесплатен тест"};
copy.fr={...copy.en,home:"Accueil",services:"Services",resellers:"Revendeurs",installation:"Installation",contact:"Contact",watch:"Regardez le monde.",withoutLimits:"Sans limites.",explore:"Découvrir nos services",freeTest:"Demander un test gratuit",ourServices:"Nos services",from:"À partir de",specialOffer:"Offre spéciale",backHome:"Retour à l’accueil",choosePlan:"Choisissez un abonnement",order:"Commander sur WhatsApp",test:"Test gratuit"};
copy.es={...copy.en,home:"Inicio",services:"Servicios",resellers:"Revendedores",installation:"Instalación",contact:"Contacto",watch:"Mira el mundo.",withoutLimits:"Sin límites.",explore:"Ver nuestros servicios",freeTest:"Solicitar prueba gratuita",ourServices:"Nuestros servicios",from:"Desde",specialOffer:"Oferta especial",backHome:"Volver al inicio",choosePlan:"Elige una suscripción",order:"Pedir por WhatsApp",test:"Prueba gratuita"};
const languageNames={en:"English",bs:"Bosanski",sr:"Srpski",hr:"Hrvatski",sq:"Shqip",mk:"Македонски",de:"Deutsch",sl:"Slovenščina",it:"Italiano",fr:"Français",es:"Español"};
let lang=localStorage.getItem("orbit-language")||"en";const tr=k=>(copy[lang]||copy.en)[k]||copy.en[k]||k;
function populateLanguages(){const select=document.querySelector("#language");if(!select)return;select.innerHTML=Object.entries(languageNames).map(([code,name])=>`<option value="${code}">${name}</option>`).join("");select.value=lang}
const serviceData={
 orbit:{name:"Orbit IPTV",icon:"O",cls:"orbit-icon",image:"assets/orbit-premium.png",lead:"Our flagship IPTV experience with three simultaneous connections, live TV, movies, series and a complete installation center.",testHours:"24",prices:[["1 month",10],["3 months",18],["6 months",28],["12 months",35],["2 years",60]],conn:"connections3"},
 lion:{name:"Lion OTT",icon:"L",cls:"lion-icon",image:"assets/lion-ott.webp",lead:"A reliable OTT service for live television, movies and series, with a complimentary 12-hour test before you subscribe.",testHours:"12",prices:[["1 month",10],["3 months",20],["6 months",35],["12 months",45],["2 years",70]],conn:"connections"},
 mega:{name:"Mega OTT",icon:"M",cls:"mega-icon",image:"assets/mega-ott.jpg",lead:"Flexible premium entertainment with easy setup, responsive playback and access across popular devices.",testHours:"24",prices:[["1 month",10],["3 months",20],["6 months",35],["12 months",45],["2 years",70]],conn:"connections"},
 strong:{name:"Strong 8K",icon:"8K",cls:"strong-icon",image:"assets/strong-8k.jpg",lead:"High-performance entertainment with dedicated applications for Smart TV, Android, Windows, macOS and web.",testHours:"24",prices:[["1 month",10],["3 months",30],["6 months",45],["12 months",55],["2 years",90]],conn:"connections"}
};
const wa=text=>`https://wa.me/${PHONE}?text=${encodeURIComponent(text)}`;
function waText(type,service){if(type==="test")return `TEST REQUEST — PANEL: ${service?.name||"Orbit IPTV"} — DURATION: ${service?.testHours||24} HOURS. Hello, please send me the test login details.`;if(type==="two-year")return "TEST REQUEST — SPECIAL 2-YEAR OFFER. Hello, please tell me which panel I can test before ordering.";if(type==="reseller")return "Hello, I want to become an Orbit IPTV reseller. Please send me information about credits and the reseller panel.";if(type==="nova")return "Hello, I would like Nova Stream Player installation and setup details for my device.";return "Hello, I would like more information about your IPTV services."}
function bindWhatsApp(service){document.querySelectorAll("[data-wa]").forEach(a=>a.href=wa(waText(a.dataset.wa,service)));}
function finishServicePage(){document.querySelectorAll(".price-card").forEach(card=>{if(card.querySelector(".pay-now"))return;const pay=document.createElement("a");pay.className="button button-outline pay-now";pay.href="#payment-options";pay.textContent="Choose payment →";card.appendChild(pay)});const hero=document.querySelector(".page-hero");if(hero&&!hero.querySelector("video")){const video=document.createElement("video");video.autoplay=true;video.muted=true;video.loop=true;video.playsInline=true;video.innerHTML='<source src="assets/orbit-promo.mp4" type="video/mp4">';hero.prepend(video)}}
function translate(){document.documentElement.lang=lang;document.querySelectorAll("[data-t]").forEach(el=>{const v=tr(el.dataset.t);if(v)el.textContent=v});const s=document.querySelector("#language");if(s)s.value=lang;}
function buildPaymentSection(){if(document.querySelector("#payment-options"))return;const section=document.createElement("section");section.id="payment-options";section.className="payment-section section-shell";section.innerHTML=`<div class="payment-intro"><div class="section-label"><span>PAY</span><i></i><b>SECURE CHECKOUT</b></div><h2>Order. Pay. Start watching.</h2><p>First choose your package and send the order on WhatsApp. Then complete payment securely using your preferred provider.</p><a class="button button-primary" data-wa="support" href="#">Order on WhatsApp →</a></div><div class="payment-options"><a class="payment-option revolut" target="_blank" rel="noopener" href="https://revolut.me/djevdjrir0"><div class="pay-symbol">R</div><div><small>INSTANT PAYMENT</small><h3>Revolut</h3><p>Pay quickly through your Revolut account.</p></div><b>↗</b></a><a class="payment-option aircash" target="_blank" rel="noopener" href="https://m3.aircash.eu/acpay/djevdjetc8"><div class="pay-symbol">A</div><div><small>SECURE LINK</small><h3>Aircash</h3><p>Complete payment through the Aircash service.</p></div><b>↗</b></a><a class="payment-option abon" target="_blank" rel="noopener" href="https://www.recharge.com/sl/si/abon"><div class="pay-symbol">AB</div><div><small>PAY BY CARD</small><h3>ABON</h3><p>Purchase ABON securely with supported debit or credit cards.</p></div><b>↗</b></a></div><div class="payment-note"><b>Important:</b> After payment, send your payment confirmation and selected package through WhatsApp so we can activate your subscription.</div>`;document.querySelector("footer").before(section)}
function buildMainNavigation(){const nav=document.querySelector(".desktop-nav");if(!nav)return;const path=location.pathname.toLowerCase();const current=new URLSearchParams(location.search).get("view")||(path.endsWith("reseller.html")?"reseller":document.body.dataset.page==="home"?"home":"");const links=[["home","index.html",tr("home")],["orbit","service.html?view=orbit","Orbit IPTV"],["lion","service.html?view=lion","Lion OTT"],["mega","service.html?view=mega","Mega OTT"],["strong","service.html?view=strong","Strong 8K"],["player","https://player.dzekiptv.store","Orbit IPTV Player"],["reseller","reseller.html",tr("resellers")],["install","https://orbitiptv.github.io/Installation-Guide",tr("installation")],["payment","#payment-options","Payment"]];nav.innerHTML=links.map(x=>`<a class="${current===x[0]?'active':''}" href="${x[1]}" ${['player','install'].includes(x[0])?'target="_blank" rel="noopener"':''}>${x[2]}</a>`).join("")}
const botAnswers={
 prices:`<b>Subscription prices</b><br><br>Orbit IPTV: €10 / 1 month, €18 / 3 months, €28 / 6 months, €35 / 12 months, €60 / 2 years.<br><br>Lion OTT and Mega OTT: €10 / 1 month, €20 / 3 months, €35 / 6 months, €45 / 12 months, €70 / 2 years.<br><br>Strong 8K: €10 / 1 month, €30 / 3 months, €45 / 6 months, €55 / 12 months, €90 / 2 years.`,
 tests:`<b>Free tests</b><br><br>Orbit IPTV: 24 hours<br>Lion OTT: 12 hours<br>Mega OTT: 24 hours<br>Strong 8K: 24 hours<br><br>Choose the service and I will prepare the correct WhatsApp request.`,
 payment:`<b>Payment options</b><br><br>You can pay with Revolut, Aircash or ABON. First place your order through WhatsApp, complete payment, then send the payment confirmation for activation.`,
 install:`<b>Installation and players</b><br><br>Orbit IPTV uses the Orbit installation guide, Orbit IPTV Player and Nova Stream Player. Lion OTT uses Rivo Player. Mega OTT has its official applications. Strong 8K supports Smart TV, Android, Windows, macOS and web.`,
 reseller:`<b>Reseller program</b><br><br>10 credits + panel: €150<br>20 credits + panel: €250<br>50 credits + panel: €500<br>100 credits + panel: €950<br><br>Free 24-hour test codes are available.`,
 contact:`<b>Contact Orbit IPTV</b><br><br>Our team can help with tests, orders, installation and activation. Use WhatsApp or Telegram below.`
};
function botReply(input){const q=input.toLowerCase();if(/price|cost|cijen|cena|koliko|preis|prezzo|çmim/.test(q))return botAnswers.prices;if(/test|trial|proba/.test(q))return botAnswers.tests;if(/pay|payment|plat|revolut|aircash|abon|kartic/.test(q))return botAnswers.payment;if(/install|player|app|smart tv|android|windows|mac|nova|rivo/.test(q))return botAnswers.install;if(/resell|preprod|panel|credit|kredit/.test(q))return botAnswers.reseller;if(/orbit/.test(q))return `<b>Orbit IPTV</b><br><br>3 connections, a free 24-hour test and subscriptions from €10. The 12-month plan is €35 and the special 2-year plan is €60.`;if(/lion/.test(q))return `<b>Lion OTT</b><br><br>1 connection, a free 12-hour test and subscriptions from €10. The 12-month plan is €45 and the special 2-year plan is €70.`;if(/mega/.test(q))return `<b>Mega OTT</b><br><br>1 connection, a free 24-hour test and subscriptions from €10. The 12-month plan is €45 and the special 2-year plan is €70.`;if(/strong|8k/.test(q))return `<b>Strong 8K</b><br><br>1 connection, a free 24-hour test and subscriptions from €10. The 12-month plan is €55 and the special 2-year plan is €90.`;if(/contact|whatsapp|telegram|help|support|kontakt/.test(q))return botAnswers.contact;return `I can help with <b>prices, free tests, installation, players, payment and reseller packages</b>.<br><br>Please choose a topic below or contact our team for a personal answer.`}
function buildSupportBot(){if(document.querySelector('#orbitBot'))return;const bot=document.createElement('div');bot.id='orbitBot';bot.className='orbit-bot';bot.innerHTML=`<button class="bot-launch" aria-label="Open Orbit support assistant"><span>✦</span><b>Ask Orbit</b><i></i></button><section class="bot-window" aria-label="Orbit support assistant"><header><div class="bot-avatar">O</div><div><b>Orbit Support</b><span><i></i> Online now</span></div><button class="bot-close" aria-label="Close">×</button></header><div class="bot-messages"><div class="bot-message bot-in">Hello 👋 I am the Orbit assistant. Ask me about our subscriptions, free tests, installation or payment.</div></div><div class="bot-quick"><button data-question="prices">💶 Prices</button><button data-question="tests">⏱ Free tests</button><button data-question="install">📺 Installation</button><button data-question="payment">💳 Payment</button><button data-question="reseller">🚀 Reseller</button></div><div class="bot-contacts"><a target="_blank" rel="noopener" href="${wa('Hello, I need help with your IPTV services.')}">WhatsApp</a><a target="_blank" rel="noopener" href="https://t.me/dzekcano72">Telegram</a></div><form class="bot-form"><input aria-label="Message" placeholder="Type your question..." autocomplete="off"><button aria-label="Send">➤</button></form></section>`;document.body.appendChild(bot);const win=bot.querySelector('.bot-window'),messages=bot.querySelector('.bot-messages'),input=bot.querySelector('input');const add=(html,out=false)=>{const el=document.createElement('div');el.className=`bot-message ${out?'bot-out':'bot-in'}`;el.innerHTML=html;messages.appendChild(el);messages.scrollTop=messages.scrollHeight};bot.querySelector('.bot-launch').onclick=()=>{win.classList.add('open');input.focus()};bot.querySelector('.bot-close').onclick=()=>win.classList.remove('open');bot.querySelectorAll('[data-question]').forEach(btn=>btn.onclick=()=>{add(btn.textContent,true);setTimeout(()=>add(botAnswers[btn.dataset.question]),250)});bot.querySelector('.bot-form').onsubmit=e=>{e.preventDefault();const value=input.value.trim();if(!value)return;add(value.replace(/[<>]/g,''),true);input.value='';setTimeout(()=>add(botReply(value)),250)}}
function renderService(key){const s=serviceData[key]||serviceData.orbit;document.title=`${s.name} | Orbit IPTV`;const prices=s.prices.map((p,i)=>`<article class="price-card ${i===2?'highlight':''}"><small>${p[0]}</small><strong>€${p[1]}</strong><p>${key==='orbit'?tr('connections3'):`1 ${tr('connections')}`} · ${tr('live')} · ${tr('movies')}</p><a class="button button-primary" href="${wa(`Hello, I would like ${s.name} for ${p[0]} (€${p[1]}).`)}">${tr('order')} →</a></article>`).join("");document.querySelector("#serviceApp").innerHTML=`<section class="page-hero"><div><div class="service-icon ${s.cls}">${s.icon}</div><div class="eyebrow"><i></i>${tr('plans')}</div><h1>${s.name}</h1><p>${s.lead}</p><div class="page-actions"><a class="button button-primary" href="${wa(waText('test',s))}">${tr('test')} →</a><a class="button button-outline" href="service.html?view=install">${tr('installation')}</a></div></div></section><section class="content-section section-shell"><div class="content-title"><small>${tr('plans')}</small><h2>${tr('choosePlan')}</h2><p>${tr('planCopy')}</p></div><div class="price-grid">${prices}</div><div class="feature-strip"><div><b>4K / FHD / HD</b><span>${tr('quality')}</span></div><div><b>${tr('live')}</b><span>Global channels</span></div><div><b>${tr('movies')}</b><span>VOD library</span></div><div><b>${s.testHours}h test</b><span>${tr('help')}</span></div></div></section>`;bindWhatsApp(s)}
const installs=[
 ["Orbit IPTV","Complete device-by-device guide for Smart TV, Android, Firestick, iOS and computers.","https://orbitiptv.github.io/Installation-Guide"],
 ["Lion OTT","Use Rivo Player for supported devices and enter the login details supplied with your subscription.","https://rivoplayer.com/"],
 ["Mega OTT","Download the official Mega OTT application for your device.","https://up.megaott.net/index.php?dirpath=./MEGAOTT/&order=3"],
 ["Strong 8K · Android","Official 4K Strong Android app.","http://download.exchange-cdn.com/apk_8k_win/4KSTRONG-6.0-v800.apk"],
 ["Strong 8K · Windows 10","8K Player for Windows 10.","http://download.exchange-cdn.com/apk_8k_win/8K.Player.Setup.0.2.0.Windows10.exe"],
 ["Strong 8K · Windows 11","8K Player for Windows 11.","http://download.exchange-cdn.com/apk_8k_win/8K.Player.Setup.0.2.0.Windows11.exe"],
 ["Strong 8K · macOS","Official 8K Player for macOS.","http://download.exchange-cdn.com/apk_gold/8k.PLAYER.OS-1.0.0.dmg"],
 ["Strong 8K · Web TV","Watch channels, movies and series in your browser.","http://8k.webplayer-only.com"],
 ["8K Player VIP","Downloader code: 2057169", "http://aftv.news/2057169"], ["8K Player VIP VOD","Downloader code: 6844860","http://aftv.news/6844860"], ["TiviMate 8K Pro","Downloader code: 3410676","http://aftv.news/3410676"], ["Fast 8K Player","Downloader code: 1315630","http://aftv.news/1315630"], ["8K Player Plus","Downloader code: 6124314","http://aftv.news/6124314"], ["8K Player Prime","Downloader code: 9149440","http://aftv.news/9149440"], ["8K Player VIP+","Downloader code: 1388878","http://aftv.news/1388878"], ["Strong Snap Old","Downloader code: 3928090","http://aftv.news/3928090"], ["Strong Power","Downloader code: 8897049","http://aftv.news/8897049"]
];
function renderInstall(){document.title="Installation Center | Orbit IPTV";document.querySelector("#serviceApp").innerHTML=`<section class="page-hero"><div><div class="eyebrow"><i></i>Orbit IPTV</div><h1>${tr('installTitle')}</h1><p>${tr('installCopy')}</p><div class="page-actions"><a class="button button-primary" href="index.html">← ${tr('backHome')}</a></div></div></section><section class="content-section section-shell"><div class="notice">Keep your username, password and server URL ready. We send these details with every activated subscription.</div><div class="install-list">${installs.map(x=>`<article class="install-card"><h3>${x[0]}</h3><p>${x[1]}</p><div class="external-links"><a class="button button-outline" target="_blank" rel="noopener" href="${x[2]}">${tr('open')} ↗</a></div></article>`).join('')}</div></section>`;bindWhatsApp()}
function renderReseller(){document.title="Reseller Program | Orbit IPTV";let credits=[["10 credits",150],["20 credits",250],["50 credits",500],["100 credits",950]];document.querySelector("#serviceApp").innerHTML=`<section class="page-hero"><div><div class="eyebrow"><i></i>${tr('business')}</div><h1>${tr('resellerTitle')}</h1><p>${tr('resellerLead')}</p><div class="page-actions"><a class="button button-primary" href="${wa(waText('reseller'))}">${tr('join')} →</a><a class="button button-outline" href="index.html">← ${tr('backHome')}</a></div></div></section><section class="content-section section-shell"><div class="content-title"><small>${tr('credits')}</small><h2>${tr('resellerProgram')}</h2></div><div class="reseller-grid">${credits.map(x=>`<article class="credit-card"><h3>${x[0]} + panel</h3><strong>€${x[1]}</strong><p>Panel included. Create and manage customer subscriptions.</p><a class="button button-primary" href="${wa(`Hello, I want the Orbit IPTV reseller package: ${x[0]} + panel (€${x[1]}).`)}">${tr('join')} →</a></article>`).join('')}</div><div class="feature-strip"><div><b>12 months</b><span>1 credit</span></div><div><b>6 months</b><span>0.5 credits</span></div><div><b>3 months</b><span>0.3 credits</span></div><div><b>1 month</b><span>0.1 credit</span></div></div><div class="notice" style="margin-top:30px"><b>${tr('hours')}:</b> ${tr('included')}.</div></section>`;bindWhatsApp()}
const servicePlayers={orbit:[
 ["Orbit Installation Guide","Complete instructions for Smart TV, Android, Firestick, iPhone and computers.","https://orbitiptv.github.io/Installation-Guide"],
 ["Orbit IPTV Player","Open the official Orbit IPTV Player and sign in with your subscription details.","https://player.dzekiptv.store"],
 ["Orbit Payment Center","Secure payment options for your subscription.","https://orbitiptv.github.io/Payment-Center"]
],lion:[["Rivo Player","Recommended player for Lion OTT. Install it, then enter the login supplied with your subscription.","https://rivoplayer.com/"]],mega:[["Mega OTT Applications","Official Mega OTT downloads for supported devices.","https://up.megaott.net/index.php?dirpath=./MEGAOTT/&order=3"]],strong:installs.slice(3)};
function renderServiceV2(key){const s=serviceData[key]||serviceData.orbit;document.title=`${s.name} | Orbit IPTV`;const prices=s.prices.map((p,i)=>`<article class="price-card ${i===2?'highlight':''}"><small>${p[0]}</small><strong>€${p[1]}</strong><p>${key==='orbit'?tr('connections3'):`1 ${tr('connections')}`} · ${tr('live')} · ${tr('movies')}</p><a class="button button-primary" href="${wa(`Hello, I would like ${s.name} for ${p[0]} (€${p[1]}).`)}">${tr('order')} →</a></article>`).join("");const art=s.image?`<div class="page-service-art ${key==='strong'?'square':''}"><img src="${s.image}" alt="${s.name}"></div>`:"";let entries=[...(servicePlayers[key]||[])];if(key==='orbit')entries.push(["Nova Stream Player","Open Nova Stream Player and sign in with the details supplied with your subscription.","https://player.dzekiptv.store"]);const players=entries.map(x=>`<article class="player-card"><h3>${x[0]}</h3><p>${x[1]}</p><a class="button button-outline" ${x[2].startsWith('http')?'target="_blank" rel="noopener"':''} href="${x[2]}">${tr('open')} ↗</a></article>`).join("");document.querySelector("#serviceApp").innerHTML=`<section class="page-hero"><div><div class="service-icon ${s.cls}">${s.icon}</div><div class="eyebrow"><i></i>${tr('plans')}</div><h1>${s.name}</h1><p>${s.lead}</p><div class="page-actions"><a class="button button-primary" href="${wa(waText('test',s))}">${tr('test')} →</a><a class="button button-outline" href="service.html?view=install">${tr('installation')}</a></div></div>${art}</section><section class="content-section section-shell"><div class="content-title"><small>${tr('plans')}</small><h2>${tr('choosePlan')}</h2><p>${tr('planCopy')}</p></div><div class="price-grid">${prices}</div><div class="feature-strip"><div><b>4K / FHD / HD</b><span>${tr('quality')}</span></div><div><b>${tr('live')}</b><span>Global channels</span></div><div><b>${tr('movies')}</b><span>VOD library</span></div><div><b>${s.testHours}h test</b><span>${tr('help')}</span></div></div></section><section class="content-section section-shell player-section"><div class="content-title"><small>${s.name}</small><h2>Players & installation</h2><p>Only the applications and instructions for ${s.name} are shown here.</p></div><div class="player-grid">${players}</div></section>`;bindWhatsApp(s)}
function init(){populateLanguages();const select=document.querySelector("#language");if(select)select.addEventListener("change",e=>{lang=e.target.value;localStorage.setItem("orbit-language",lang);location.reload()});translate();buildMainNavigation();buildPaymentSection();if(document.body.dataset.page==="service"){const path=location.pathname.toLowerCase();const ownReseller=path.endsWith("/reseller.html");const view=ownReseller?"reseller":(new URLSearchParams(location.search).get("view")||"orbit");if(view==="install")renderInstall();else if(view==="reseller")renderReseller();else renderServiceV2(view);finishServicePage();bindWhatsApp()}else bindWhatsApp();buildSupportBot()}
init();
