const extraCss=document.createElement("link");extraCss.rel="stylesheet";extraCss.href="styles-extra.css";document.head.appendChild(extraCss);
const PHONE="38669843976";
const copy={
en:{home:"Home",services:"Services",resellers:"Resellers",installation:"Installation",contact:"Contact",eyebrow:"Premium entertainment, your way",watch:"Watch the world.",withoutLimits:"Without limits.",heroCopy:"Live television, movies and series from around the world — beautifully organized and ready on every screen.",explore:"Explore our services",freeTest:"Request a free test",premiumServices:"premium services",support:"customer support",quality:"picture quality",discover:"Discover",ourServices:"Our services",chooseExperience:"Choose your viewing experience.",servicesCopy:"Four carefully selected services. One simple goal: reliable entertainment, exactly how you want it.",orbitCopy:"Our flagship service with 3 simultaneous connections and a complete installation center.",lionCopy:"A smooth, reliable OTT experience with a complimentary 12-hour test.",megaCopy:"A flexible entertainment package with simple setup across popular devices.",strongCopy:"Premium performance, dedicated apps and broad device compatibility.",from:"From",specialOffer:"Special offer",twoYears:"Two years. One great price.",dealCopy:"Commit to more entertainment and save. Our best long-term value is available across all four services.",claim:"Claim this offer",business:"A BUSINESS OPPORTUNITY",grow:"Grow with Orbit IPTV.",resellerCopy:"Get your own reseller panel, create subscriptions in seconds and build recurring income.",resellerProgram:"View reseller program",backHome:"Back to Home",allServices:"All services",plans:"Simple, transparent plans",choosePlan:"Choose a subscription",planCopy:"No contract. Friendly support. Your entertainment starts within minutes.",order:"Order on WhatsApp",test:"Request free test",features:"What is included",live:"Live television",movies:"Movies & series",device:"Popular devices",help:"Friendly support",installTitle:"Installation center",installCopy:"Choose your service and device. These official apps and players make setup quick and simple.",open:"Open / download",resellerTitle:"Become an Orbit IPTV reseller",resellerLead:"Create subscriptions for your customers with your own panel. Free 24-hour test codes are available.",credits:"Credits + panel",join:"Join on WhatsApp",periods:"Subscription periods",hours:"24-hour test",included:"available free",connections:"connection",connections3:"3 connections"},
bs:{home:"Početna",services:"Usluge",resellers:"Preprodavači",installation:"Instalacija",contact:"Kontakt",eyebrow:"Premium zabava, po vašoj mjeri",watch:"Gledajte svijet.",withoutLimits:"Bez granica.",heroCopy:"Televizija uživo, filmovi i serije iz cijelog svijeta — uredno složeni i dostupni na svakom ekranu.",explore:"Pogledajte ponudu",freeTest:"Zatraži besplatan test",premiumServices:"premium usluge",support:"korisnička podrška",quality:"kvaliteta slike",discover:"Otkrijte",ourServices:"Naše usluge",chooseExperience:"Izaberite svoje TV iskustvo.",servicesCopy:"Četiri pažljivo odabrane usluge. Jedan cilj: pouzdana zabava baš po vašoj želji.",orbitCopy:"Naša glavna usluga s 3 istovremene konekcije i kompletnim instalacijskim centrom.",lionCopy:"Stabilno OTT iskustvo uz besplatan test od 12 sati.",megaCopy:"Fleksibilan paket zabave s jednostavnom instalacijom na popularnim uređajima.",strongCopy:"Premium performanse, posebne aplikacije i široka podrška za uređaje.",from:"Od",specialOffer:"Posebna ponuda",twoYears:"Dvije godine. Jedna odlična cijena.",dealCopy:"Više zabave uz veću uštedu. Najbolja dugoročna ponuda za sve četiri usluge.",claim:"Zatraži ponudu",business:"POSLOVNA PRILIKA",grow:"Rastite uz Orbit IPTV.",resellerCopy:"Dobijte svoj panel, kreirajte pretplate za nekoliko sekundi i razvijajte stalnu zaradu.",resellerProgram:"Program za preprodavače",backHome:"Nazad na početnu",allServices:"Sve usluge",plans:"Jednostavne i jasne cijene",choosePlan:"Izaberite pretplatu",planCopy:"Bez ugovora. Ljubazna podrška. Zabava počinje za nekoliko minuta.",order:"Naruči na WhatsApp",test:"Zatraži besplatan test",features:"Šta je uključeno",live:"TV uživo",movies:"Filmovi i serije",device:"Popularni uređaji",help:"Ljubazna podrška",installTitle:"Centar za instalaciju",installCopy:"Izaberite uslugu i uređaj. Službene aplikacije i playeri omogućavaju brzo podešavanje.",open:"Otvori / preuzmi",resellerTitle:"Postanite Orbit IPTV preprodavač",resellerLead:"Kreirajte pretplate za svoje klijente preko vlastitog panela. Besplatni test kodovi od 24 sata su dostupni.",credits:"Krediti + panel",join:"Prijavi se na WhatsApp",periods:"Trajanje pretplate",hours:"24-satni test",included:"dostupan besplatno",connections:"konekcija",connections3:"3 konekcije"}
};
copy.de={...copy.en,home:"Start",services:"Dienste",resellers:"Wiederverkäufer",installation:"Installation",contact:"Kontakt",freeTest:"Kostenlosen Test anfordern",backHome:"Zurück zur Startseite",order:"Auf WhatsApp bestellen",test:"Kostenlosen Test anfordern"};
copy.sl={...copy.en,home:"Domov",services:"Storitve",resellers:"Prodajalci",installation:"Namestitev",contact:"Kontakt",freeTest:"Zahtevajte brezplačni test",backHome:"Nazaj domov",order:"Naroči prek WhatsAppa",test:"Brezplačni test"};
copy.it={...copy.en,home:"Home",services:"Servizi",resellers:"Rivenditori",installation:"Installazione",contact:"Contatti",freeTest:"Richiedi una prova gratuita",backHome:"Torna alla Home",order:"Ordina su WhatsApp",test:"Prova gratuita"};
let lang=localStorage.getItem("orbit-language")||"en";const tr=k=>(copy[lang]||copy.en)[k]||copy.en[k]||k;
const serviceData={
 orbit:{name:"Orbit IPTV",icon:"O",cls:"orbit-icon",image:"assets/orbit-premium.png",lead:"Our flagship IPTV experience with three simultaneous connections, live TV, movies, series and a complete installation center.",testHours:"24",prices:[["1 month",10],["3 months",18],["6 months",28],["12 months",35],["2 years",60]],conn:"connections3"},
 lion:{name:"Lion OTT",icon:"L",cls:"lion-icon",image:"assets/lion-ott.webp",lead:"A reliable OTT service for live television, movies and series, with a complimentary 12-hour test before you subscribe.",testHours:"12",prices:[["1 month",10],["3 months",20],["6 months",35],["12 months",45],["2 years",70]],conn:"connections"},
 mega:{name:"Mega OTT",icon:"M",cls:"mega-icon",image:"assets/mega-ott.jpg",lead:"Flexible premium entertainment with easy setup, responsive playback and access across popular devices.",testHours:"12",prices:[["1 month",10],["3 months",20],["6 months",35],["12 months",45],["2 years",70]],conn:"connections"},
 strong:{name:"Strong 8K",icon:"8K",cls:"strong-icon",image:"assets/strong-8k.jpg",lead:"High-performance entertainment with dedicated applications for Smart TV, Android, Windows, macOS and web.",testHours:"12",prices:[["1 month",10],["3 months",30],["6 months",45],["12 months",55],["2 years",90]],conn:"connections"}
};
const wa=text=>`https://wa.me/${PHONE}?text=${encodeURIComponent(text)}`;
function waText(type,service){if(type==="test")return `Hello, I would like a free ${service?.testHours||24}-hour test for ${service?.name||"Orbit IPTV"}.`;if(type==="two-year")return "Hello, I am interested in the special 2-year offer. Please send me more information.";if(type==="reseller")return "Hello, I want to become an Orbit IPTV reseller. Please send me information about credits and the panel.";return "Hello, I would like more information about your IPTV services."}
function bindWhatsApp(service){document.querySelectorAll("[data-wa]").forEach(a=>a.href=wa(waText(a.dataset.wa,service)));}
function finishServicePage(){document.querySelectorAll(".price-card").forEach(card=>{if(card.querySelector(".pay-now"))return;const pay=document.createElement("a");pay.className="button button-outline pay-now";pay.href="https://orbitiptv.github.io/Payment-Center";pay.target="_blank";pay.rel="noopener";pay.textContent="Payment Center →";card.appendChild(pay)});const hero=document.querySelector(".page-hero");if(hero&&!hero.querySelector("video")){const video=document.createElement("video");video.autoplay=true;video.muted=true;video.loop=true;video.playsInline=true;video.innerHTML='<source src="assets/orbit-promo.mp4" type="video/mp4">';hero.prepend(video)}}
function translate(){document.documentElement.lang=lang;document.querySelectorAll("[data-t]").forEach(el=>{const v=tr(el.dataset.t);if(v)el.textContent=v});const s=document.querySelector("#language");if(s)s.value=lang;}
function buildMainNavigation(){const nav=document.querySelector(".desktop-nav");if(!nav)return;const path=location.pathname.toLowerCase();const current=new URLSearchParams(location.search).get("view")||(path.endsWith("reseller.html")?"reseller":document.body.dataset.page==="home"?"home":"");const links=[["home","index.html",tr("home")],["orbit","service.html?view=orbit","Orbit IPTV"],["lion","service.html?view=lion","Lion OTT"],["mega","service.html?view=mega","Mega OTT"],["strong","service.html?view=strong","Strong 8K"],["player","https://player.dzekiptv.store","Web Player"],["reseller","reseller.html",tr("resellers")],["install","https://orbitiptv.github.io/Installation-Guide",tr("installation")],["payment","https://orbitiptv.github.io/Payment-Center","Payment"]];nav.innerHTML=links.map(x=>`<a class="${current===x[0]?'active':''}" href="${x[1]}" ${['player','install','payment'].includes(x[0])?'target="_blank" rel="noopener"':''}>${x[2]}</a>`).join("")}
function renderService(key){const s=serviceData[key]||serviceData.orbit;document.title=`${s.name} | Orbit IPTV`;const prices=s.prices.map((p,i)=>`<article class="price-card ${i===2?'highlight':''}"><small>${p[0]}</small><strong>€${p[1]}</strong><p>${key==='orbit'?tr('connections3'):`1 ${tr('connections')}`} · ${tr('live')} · ${tr('movies')}</p><a class="button button-primary" href="${wa(`Hello, I would like ${s.name} for ${p[0]} (€${p[1]}).`)}">${tr('order')} →</a></article>`).join("");document.querySelector("#serviceApp").innerHTML=`<section class="page-hero"><div><div class="service-icon ${s.cls}">${s.icon}</div><div class="eyebrow"><i></i>${tr('plans')}</div><h1>${s.name}</h1><p>${s.lead}</p><div class="page-actions"><a class="button button-primary" href="${wa(waText('test',s))}">${tr('test')} →</a><a class="button button-outline" href="service.html?view=install">${tr('installation')}</a></div></div></section><section class="content-section section-shell"><div class="content-title"><small>${tr('plans')}</small><h2>${tr('choosePlan')}</h2><p>${tr('planCopy')}</p></div><div class="price-grid">${prices}</div><div class="feature-strip"><div><b>4K / FHD / HD</b><span>${tr('quality')}</span></div><div><b>${tr('live')}</b><span>Global channels</span></div><div><b>${tr('movies')}</b><span>VOD library</span></div><div><b>${s.testHours}h test</b><span>${tr('help')}</span></div></div></section>`;bindWhatsApp(s)}
const installs=[
 ["Orbit IPTV","Complete device-by-device guide for Smart TV, Android, Firestick, iOS and computers.","https://orbitiptv.github.io/Installation-Guide"],
 ["Lion OTT","Use Rivo Player for supported devices and enter the login details supplied with your subscription.","https://rivoplayer.com/"],
 ["Mega OTT","Download the official Mega OTT application for your device.","https://up.megaott.net/index.php?dirpath=./MEGAOTT/&order=3"],
 ["Strong 8K · Android","Official 4K Strong Android app.","http://download.exchange-cdn.com/apk_8k_win/4KSTRONG-6.0-v800.apk"],
 ["Strong 8K · Windows 10","8K Player for Windows 10.","http://download.exchange-cdn.com/apk_8k_win/8K.Player.Setup.0.2.0.Windows10.exe"],
 ["Strong 8K · Windows 11","8K Player for Windows 11.","http://download.exchange-cdn.com/apk_8k_win/8K.Player.Setup.0.2.0.Windows11.exe"],
 ["Strong 8K · macOS","Official 8K Player for macOS.","http://download.exchange-cdn.com/apk_gold/8k.PLAYER.OS-1.0.0.dmg"],
 ["Strong 8K · Web TV","Watch channels, movies and series in your browser.","http://8k.webplayer-only.com"],
 ["8K Player VIP","Downloader code: 2057169", "http://aftv.news/2057169"], ["8K Player VIP VOD","Downloader code: 6844860","http://aftv.news/6844860"], ["TiviMate 8K Pro","Downloader code: 3410676","http://aftv.news/3410676"], ["Fast 8K Player","Downloader code: 1315630","http://aftv.news/1315630"], ["8K Player Plus","Downloader code: 6124314","http://aftv.news/6124314"], ["8K Player Prime","Downloader code: 9149440","http://aftv.news/9149440"], ["8K Player VIP+","Downloader code: 1388878","http://aftv.news/1388878"], ["Strong Snap Old","Downloader code: 3928090","http://aftv.news/3928090"], ["Strong Power","Downloader code: 8897049","http://aftv.news/8897049"]
];
function renderInstall(){document.title="Installation Center | Orbit IPTV";document.querySelector("#serviceApp").innerHTML=`<section class="page-hero"><div><div class="eyebrow"><i></i>Orbit IPTV</div><h1>${tr('installTitle')}</h1><p>${tr('installCopy')}</p><div class="page-actions"><a class="button button-primary" href="index.html">← ${tr('backHome')}</a></div></div></section><section class="content-section section-shell"><div class="notice">Keep your username, password and server URL ready. We send these details with every activated subscription.</div><div class="install-list">${installs.map(x=>`<article class="install-card"><h3>${x[0]}</h3><p>${x[1]}</p><div class="external-links"><a class="button button-outline" target="_blank" rel="noopener" href="${x[2]}">${tr('open')} ↗</a></div></article>`).join('')}</div></section>`;bindWhatsApp()}
function renderReseller(){document.title="Reseller Program | Orbit IPTV";let credits=[["10 credits",150],["20 credits",250],["50 credits",500],["100 credits",950]];document.querySelector("#serviceApp").innerHTML=`<section class="page-hero"><div><div class="eyebrow"><i></i>${tr('business')}</div><h1>${tr('resellerTitle')}</h1><p>${tr('resellerLead')}</p><div class="page-actions"><a class="button button-primary" href="${wa(waText('reseller'))}">${tr('join')} →</a><a class="button button-outline" href="index.html">← ${tr('backHome')}</a></div></div></section><section class="content-section section-shell"><div class="content-title"><small>${tr('credits')}</small><h2>${tr('resellerProgram')}</h2></div><div class="reseller-grid">${credits.map(x=>`<article class="credit-card"><h3>${x[0]} + panel</h3><strong>€${x[1]}</strong><p>Panel included. Create and manage customer subscriptions.</p><a class="button button-primary" href="${wa(`Hello, I want the Orbit IPTV reseller package: ${x[0]} + panel (€${x[1]}).`)}">${tr('join')} →</a></article>`).join('')}</div><div class="feature-strip"><div><b>12 months</b><span>1 credit</span></div><div><b>6 months</b><span>0.5 credits</span></div><div><b>3 months</b><span>0.3 credits</span></div><div><b>1 month</b><span>0.1 credit</span></div></div><div class="notice" style="margin-top:30px"><b>${tr('hours')}:</b> ${tr('included')}.</div></section>`;bindWhatsApp()}
const servicePlayers={orbit:[
 ["Orbit Installation Guide","Complete instructions for Smart TV, Android, Firestick, iPhone and computers.","https://orbitiptv.github.io/Installation-Guide"],
 ["Orbit Web Player","Watch directly in your browser.","https://player.dzekiptv.store"],
 ["Orbit Payment Center","Secure payment options for your subscription.","https://orbitiptv.github.io/Payment-Center"]
],lion:[["Rivo Player","Recommended player for Lion OTT. Install it, then enter the login supplied with your subscription.","https://rivoplayer.com/"]],mega:[["Mega OTT Applications","Official Mega OTT downloads for supported devices.","https://up.megaott.net/index.php?dirpath=./MEGAOTT/&order=3"]],strong:installs.slice(3)};
function renderServiceV2(key){const s=serviceData[key]||serviceData.orbit;document.title=`${s.name} | Orbit IPTV`;const prices=s.prices.map((p,i)=>`<article class="price-card ${i===2?'highlight':''}"><small>${p[0]}</small><strong>€${p[1]}</strong><p>${key==='orbit'?tr('connections3'):`1 ${tr('connections')}`} · ${tr('live')} · ${tr('movies')}</p><a class="button button-primary" href="${wa(`Hello, I would like ${s.name} for ${p[0]} (€${p[1]}).`)}">${tr('order')} →</a></article>`).join("");const art=s.image?`<div class="page-service-art ${key==='strong'?'square':''}"><img src="${s.image}" alt="${s.name}"></div>`:"";const players=(servicePlayers[key]||[]).map(x=>`<article class="player-card"><h3>${x[0]}</h3><p>${x[1]}</p><a class="button button-outline" target="_blank" rel="noopener" href="${x[2]}">${tr('open')} ↗</a></article>`).join("");document.querySelector("#serviceApp").innerHTML=`<section class="page-hero"><div><div class="service-icon ${s.cls}">${s.icon}</div><div class="eyebrow"><i></i>${tr('plans')}</div><h1>${s.name}</h1><p>${s.lead}</p><div class="page-actions"><a class="button button-primary" href="${wa(waText('test',s))}">${tr('test')} →</a><a class="button button-outline" href="service.html?view=install">${tr('installation')}</a></div></div>${art}</section><section class="content-section section-shell"><div class="content-title"><small>${tr('plans')}</small><h2>${tr('choosePlan')}</h2><p>${tr('planCopy')}</p></div><div class="price-grid">${prices}</div><div class="feature-strip"><div><b>4K / FHD / HD</b><span>${tr('quality')}</span></div><div><b>${tr('live')}</b><span>Global channels</span></div><div><b>${tr('movies')}</b><span>VOD library</span></div><div><b>${s.testHours}h test</b><span>${tr('help')}</span></div></div></section><section class="content-section section-shell player-section"><div class="content-title"><small>${s.name}</small><h2>Players & installation</h2><p>Only the applications and instructions for ${s.name} are shown here.</p></div><div class="player-grid">${players}</div></section>`;bindWhatsApp(s)}
function init(){const select=document.querySelector("#language");if(select)select.addEventListener("change",e=>{lang=e.target.value;localStorage.setItem("orbit-language",lang);location.reload()});translate();buildMainNavigation();if(document.body.dataset.page==="service"){const path=location.pathname.toLowerCase();const ownReseller=path.endsWith("/reseller.html");const view=ownReseller?"reseller":(new URLSearchParams(location.search).get("view")||"orbit");if(view==="install")renderInstall();else if(view==="reseller")renderReseller();else renderServiceV2(view);finishServicePage()}else bindWhatsApp()}
init();
