(()=>{
'use strict';
if(document.getElementById('orbit-chat-toggle'))return;
const style=document.createElement('style');style.textContent=`#orbit-chat-toggle{position:fixed;right:20px;bottom:20px;z-index:9998;border:0;border-radius:30px;background:#36c6ee;color:#061421;padding:15px 20px;font:700 15px system-ui;box-shadow:0 8px 32px #0006;cursor:pointer}#orbit-chat{position:fixed;right:20px;bottom:82px;z-index:9998;width:min(380px,calc(100vw - 32px));height:min(550px,calc(100dvh - 110px));background:#101e30;color:#fff;border:1px solid #486176;border-radius:18px;box-shadow:0 15px 50px #0008;display:flex;flex-direction:column;font:15px/1.5 system-ui;overflow:hidden}#orbit-chat[hidden]{display:none}#orbit-chat header{position:static;padding:14px 16px;display:flex;justify-content:space-between;background:#172d43}#orbit-chat button{cursor:pointer;font:inherit}#orbit-chat-close{background:none;border:0;color:white;font-size:24px}#orbit-chat-log{padding:14px;overflow-y:auto;flex:1}#orbit-chat-log p{padding:10px 13px;background:#20374b;border-radius:12px;margin:0 0 10px;white-space:pre-line}#orbit-chat-log p.customer{background:#235367;margin-left:25px}#orbit-chat-options{display:flex;flex-wrap:wrap;gap:7px;padding:0 12px 12px}#orbit-chat-options button{background:#20374b;color:#fff;border:1px solid #61839d;border-radius:20px;padding:6px 10px}#orbit-chat form{display:flex;gap:8px;padding:12px;border-top:1px solid #405267}#orbit-chat-input{min-width:0;flex:1;border-radius:8px;background:#fff;color:#111;padding:10px;border:0;font:inherit}#orbit-chat form button{background:#36c6ee;color:#071725;border:0;border-radius:8px;padding:9px}#orbit-chat-log a{display:block;background:#36c6ee;color:#051a27;text-decoration:none;border-radius:10px;padding:10px 12px;font-weight:700;margin-bottom:10px}#orbit-chat-note{font-size:12px;padding:0 13px 10px;color:#b3c9da}@media(max-width:450px){#orbit-chat{right:16px}#orbit-chat-toggle{right:16px}}`;document.head.append(style);
const toggle=document.createElement('button');toggle.id='orbit-chat-toggle';toggle.textContent='💬 Questions? Try a free test';toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-controls','orbit-chat');document.body.append(toggle);
const panel=document.createElement('section');panel.id='orbit-chat';panel.hidden=true;panel.setAttribute('aria-label','Orbit IPTV assistant');panel.innerHTML='<header><strong>Orbit IPTV assistant</strong><button id="orbit-chat-close" aria-label="Close chat">×</button></header><div id="orbit-chat-log" role="log" aria-live="polite"></div><div id="orbit-chat-options"></div><form><input id="orbit-chat-input" aria-label="Your question" placeholder="Ask about prices, tests or setup…" maxlength="500" autocomplete="off"><button type="submit">Send</button></form><div id="orbit-chat-note">Automatic answers to common questions. Our team handles activation and account support.</div>';document.body.append(panel);
const log=panel.querySelector('#orbit-chat-log'),input=panel.querySelector('input');
function say(text,customer=false){const p=document.createElement('p');p.textContent=text;if(customer){p.className='customer notranslate';p.setAttribute('translate','no')}log.append(p);log.scrollTop=log.scrollHeight}
function link(text,url){const a=document.createElement('a');a.textContent=text;a.href=url;a.target='_blank';a.rel='noopener noreferrer';log.append(a);log.scrollTop=log.scrollHeight}
const whats=text=>'https://wa.me/38669843976?text='+encodeURIComponent(text);
function trials(){say('Try it on your own device before choosing a plan. Orbit IPTV offers a free 24-hour test; Lion OTT offers a free 12-hour test. Which service would you like to try?');link('Request Orbit IPTV — free 24-hour test',whats('Hello, I would like a free 24-hour Orbit IPTV test. My device is: '));link('Request Lion OTT — free 12-hour test',whats('Hello, I would like a free 12-hour Lion OTT test. My device is: '))}
function reply(question){const q=question.toLowerCase();if(/price|cost|cijen|cena|koliko|preis|prezzo|цена|çmim/.test(q)){say('Orbit IPTV: 1 month €10, 3 months €20, 6 months €28, 12 months €35, 24 months €60. Includes 3 simultaneous connections.\n\nLion OTT: 1 month €10, 3 months €20, 6 months €35, 12 months €45, 24 months €70. Includes 1 connection.\n\nA free test helps you check the service on your device before subscribing.');trials()}else if(/install|player|setup|smart|fire|android|iphone|instal|uređ|ured|gerät|namest|инстал/.test(q)){say('You can find setup instructions for supported TVs, phones and computers in our latest guide. Lion OTT uses Rivo Player. Tell our team your device model when requesting a test so they can help you get started.');link('Open the latest installation guide','https://orbitiptv.github.io/Installation-Guide/');trials()}else if(/vpn|buffer|freez|block|ne radi|problem|grešk|gresk|error/.test(q)){say('For connection problems, check your internet connection and restart your device and router. Our VPN guide has instructions for supported devices. For login errors, contact our team with your device model and the error message.');link('Open VPN guide','https://orbitiptv.github.io/vpn.html');link('Get help on WhatsApp',whats('Hello, I need help with my IPTV service. My device and error message are: '))}else if(/channel|kanal|film|movie|series|serij|sender|канал/.test(q)){say('Browse the full catalog by country and category, including live channels, movies and series. A test lets you check the content available with your account.');link('Browse channels, movies and series','https://orbitiptv.github.io/channel-list/');trials()}else if(/resell|preprod|credit|kredit|panel/.test(q)){say('Our reseller program lets you buy credits and create subscriptions for your customers. View the credit packages or contact our team to get started.');link('View reseller packages','https://orbitiptv.github.io/reseller.html');link('Ask about reseller access',whats('Hello, I would like information about your reseller program.'))}else if(/test|trial|proba|prob|besplat|free|orbit|lion|тест/.test(q)){trials()}else{say('I can help with prices, free tests, channels, installation and reseller packages. For an account-specific question, our team can help directly. Want to see whether the service suits you? Start with a free test.');trials();link('Talk to our team',whats('Hello, I have a question about your IPTV services: '+question))}}
for(const [label,topic]of [['Free test','test'],['Prices','prices'],['Channels','channels'],['Installation','installation'],['VPN / help','vpn'],['Reseller','reseller']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>reply(topic));panel.querySelector('#orbit-chat-options').append(b)}
let welcomed=false;function open(value){panel.hidden=!value;toggle.setAttribute('aria-expanded',String(value));if(value){if(!welcomed){say('Welcome! Looking for TV, movies or sports? I can help you find the right service. You can try Orbit IPTV free for 24 hours or Lion OTT free for 12 hours before choosing a plan. Pick a topic below.');welcomed=true}input.focus()}else toggle.focus()}
toggle.addEventListener('click',()=>open(panel.hidden));panel.querySelector('#orbit-chat-close').addEventListener('click',()=>open(false));panel.addEventListener('keydown',e=>{if(e.key==='Escape')open(false)});panel.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const q=input.value.trim();if(!q)return;say(q,true);input.value='';reply(q)});
})();
