(()=>{
'use strict';
if(document.getElementById('orbit-chat-toggle'))return;
const style=document.createElement('style');style.textContent=`#orbit-chat-toggle{position:fixed;right:20px;bottom:20px;z-index:9998;border:0;border-radius:30px;background:linear-gradient(110deg,#7650eb,#487bf5);color:#fff;padding:15px 20px;font:700 15px system-ui;box-shadow:0 8px 32px #0006;cursor:pointer}#orbit-chat{position:fixed;right:20px;bottom:82px;z-index:9998;width:min(380px,calc(100vw - 32px));height:min(550px,calc(100dvh - 110px));background:#101e30;color:#fff;border:1px solid #486176;border-radius:18px;box-shadow:0 15px 50px #0008;display:flex;flex-direction:column;font:15px/1.5 system-ui;overflow:hidden}#orbit-chat[hidden]{display:none}#orbit-chat header{position:static;padding:14px 16px;display:flex;justify-content:space-between;background:#172d43}#orbit-chat button{cursor:pointer;font:inherit}#orbit-chat-close{background:none;border:0;color:white;font-size:24px}#orbit-chat-log{padding:14px;overflow-y:auto;flex:1}#orbit-chat-log p{padding:10px 13px;background:#20374b;border-radius:12px;margin:0 0 10px;white-space:pre-line}#orbit-chat-log p.customer{background:#235367;margin-left:25px}#orbit-chat-options{display:flex;flex-wrap:wrap;gap:7px;padding:0 12px 12px}#orbit-chat-options button{background:#20374b;color:#fff;border:1px solid #61839d;border-radius:20px;padding:6px 10px}#orbit-chat form{display:flex;gap:8px;padding:12px;border-top:1px solid #405267}#orbit-chat-input{min-width:0;flex:1;border-radius:8px;background:#fff;color:#111;padding:10px;border:0;font:inherit}#orbit-chat form button{background:#7650eb;color:#fff;border:0;border-radius:8px;padding:9px}#orbit-chat-log a{display:block;background:#7650eb;color:#fff;text-decoration:none;border-radius:10px;padding:10px 12px;font-weight:700;margin-bottom:10px}#orbit-chat-note{font-size:12px;padding:0 13px 10px;color:#b3c9da}@media(max-width:450px){#orbit-chat{right:16px}#orbit-chat-toggle{right:16px}}`;document.head.append(style);
const toggle=document.createElement('button');toggle.id='orbit-chat-toggle';toggle.textContent='💬 Welcome! Need help?';toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-controls','orbit-chat');document.body.append(toggle);
const panel=document.createElement('section');panel.id='orbit-chat';panel.hidden=true;panel.setAttribute('aria-label','Orbit IPTV assistant');panel.innerHTML='<header><strong>Orbit IPTV assistant</strong><button id="orbit-chat-close" aria-label="Close chat">×</button></header><div id="orbit-chat-log" role="log" aria-live="polite"></div><div id="orbit-chat-options"></div><form><input id="orbit-chat-input" aria-label="Your question" placeholder="How can we help you?" maxlength="500" autocomplete="off"><button type="submit">Send</button></form><div id="orbit-chat-note">Automated welcome assistant. Questions are handled by our team on WhatsApp.</div>';document.body.append(panel);
const log=panel.querySelector('#orbit-chat-log'),input=panel.querySelector('input');
function say(text,customer=false){const p=document.createElement('p');p.textContent=text;if(customer){p.className='customer notranslate';p.setAttribute('translate','no')}log.append(p);log.scrollTop=log.scrollHeight}
function link(text,url){const a=document.createElement('a');a.textContent=text;a.href=url;a.target='_blank';a.rel='noopener noreferrer';log.append(a);log.scrollTop=log.scrollHeight}
const whats=text=>'https://wa.me/38669843976?text='+encodeURIComponent(text);
function trials(){say('Try it on your own device before choosing a plan. Orbit IPTV offers a free 24-hour test; Lion OTT offers a free 12-hour test. Which service would you like to try?');link('Request Orbit IPTV — free 24-hour test',whats('Hello, I would like a free 24-hour Orbit IPTV test. My device is: '));link('Request Lion OTT — free 12-hour test',whats('Hello, I would like a free 12-hour Lion OTT test. My device is: '))}
function reply(question){
 say('Our team will be happy to help. Tap below to continue on WhatsApp. Your question will be included in the message, ready for you to send.');
 link('Continue on WhatsApp · +386 69 843 976',whats('Hello Orbit IPTV, '+question));
}
for(const [label,topic]of [['Free test','test'],['Prices','prices'],['Channels','channels'],['Installation','installation'],['VPN / help','vpn'],['Reseller','reseller']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>{say(label,true);reply('I would like help with '+label.toLowerCase()+'.')});panel.querySelector('#orbit-chat-options').append(b)}
let welcomed=false;function open(value){panel.hidden=!value;toggle.setAttribute('aria-expanded',String(value));if(value){if(!welcomed){say('Hello and welcome to Orbit IPTV! 👋 How can we help you today? Ask a question or choose a topic below, and we will connect you with our team on WhatsApp.');welcomed=true}input.focus()}else toggle.focus()}
toggle.addEventListener('click',()=>open(panel.hidden));panel.querySelector('#orbit-chat-close').addEventListener('click',()=>open(false));panel.addEventListener('keydown',e=>{if(e.key==='Escape')open(false)});panel.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const q=input.value.trim();if(!q)return;say(q,true);input.value='';reply(q)});
})();
