(function(){
const install='https://orbitiptv.github.io/Installation-Guide';
const resellerCredits=[['2 Credits','€50 EUR'],['5 Credits','€100 EUR'],['10 Credits','€150 EUR'],['20 Credits','€250 EUR'],['50 Credits','€500 EUR'],['100 Credits','€950 EUR']];
const subscriptions=[['24 Hour (free trial)','0 credit'],['1 Month','0.1 credit'],['3 Month','0.25 credit'],['6 Month','0.5 credit'],['1 Year','1 credit']];
function table(rows,a,b){return `<div class="orbit-table"><table><thead><tr><th>${a}</th><th>${b}</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td></tr>`).join('')}</tbody></table></div>`}
function resellerSection(){return `<section class="unified-reseller section-shell"><div class="section-label"><span>04</span><i></i><b>RESELLER PROGRAM</b></div><div class="unified-heading"><h2>Build your business with Orbit IPTV.</h2><p>Choose a credit package, create customer subscriptions and manage them from your reseller panel.</p></div><div class="unified-tables"><article><h3>Credit packages</h3>${table(resellerCredits,'Credits','Price')}</article><article><h3>Subscription credit cost</h3>${table(subscriptions,'IPTV subscription duration','Credit cost')}</article></div><div class="unified-actions"><a class="button button-primary" data-wa="reseller" href="#">Join on WhatsApp →</a><a class="button button-outline" href="reseller.html">Reseller details →</a></div></section>`}
function installationSection(){return `<section class="unified-install section-shell"><div><div class="section-label"><span>05</span><i></i><b>INSTALLATION</b></div><h2>Setup for every screen.</h2><p>Follow the complete OrbitTV guide for Smart TV, Android, Firestick, iPhone, computers and other supported devices.</p><a class="button button-primary" href="${install}" target="_blank" rel="noopener">Open Installation Guide →</a></div><img src="assets/orbit-logo.png" alt="OrbitTV installation guide"></section>`}
function home(){const main=document.querySelector('main');if(!main)return;document.querySelector('.reseller-banner')?.remove();const payment=document.querySelector('#payments');const wrap=document.createElement('div');wrap.innerHTML=resellerSection()+installationSection();while(wrap.firstChild)main.insertBefore(wrap.firstChild,payment||null)}
function reseller(){const content=document.querySelector('.content-section');if(!content)return;content.innerHTML=`<div class="content-title"><small>CREDITS + PANEL</small><h2>OrbitTV Reseller Program</h2><p>Create and manage subscriptions for your customers.</p></div><div class="unified-tables"><article><h3>Credit packages</h3>${table(resellerCredits,'Credits','Price in EUR')}</article><article><h3>IPTV account pricing</h3>${table(subscriptions,'IPTV subscription duration','Credit cost')}</article></div><div class="unified-actions"><a class="button button-primary" href="https://wa.me/38669843976?text=${encodeURIComponent('Hello, I want to become an OrbitTV reseller. Please send me reseller panel information.')}" target="_blank" rel="noopener">Join on WhatsApp →</a></div>`}
function navigation(){document.querySelectorAll('.desktop-nav a, footer a, .page-actions a').forEach(a=>{const t=a.textContent.trim().toLowerCase();if(['installation','instalacija','namestitev','installazione'].includes(t)){a.href=install;a.target='_blank';a.rel='noopener'}if(t==='login'||t==='log in'||t==='sign up')a.remove()})}
function channelPage(){if(!location.pathname.includes('channel-list'))return;document.querySelectorAll('[data-topic]').forEach(a=>{const t=(a.dataset.topic||'').toLowerCase();if(['blog','system status','legal information'].includes(t))a.remove()});const account=[...document.querySelectorAll('footer section')].find(s=>/account/i.test(s.textContent));account?.remove();}
function bind(){document.querySelectorAll('[data-wa="reseller"]').forEach(a=>a.href='https://wa.me/38669843976?text='+encodeURIComponent('Hello, I want to become an OrbitTV reseller. Please send me reseller panel information.'))}
function init(){navigation();channelPage();if(document.body.dataset.page==='home')home();if(location.pathname.endsWith('/reseller.html')||new URLSearchParams(location.search).get('view')==='reseller')reseller();bind()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();

