(function(){
const install='https://orbitiptv.github.io/Installation-Guide';
const resellerCredits=[['2 Credits','€50 EUR'],['5 Credits','€100 EUR'],['10 Credits','€150 EUR'],['20 Credits','€250 EUR'],['50 Credits','€500 EUR'],['100 Credits','€950 EUR']];
const subscriptions=[['24 Hour (free trial)','0 credit'],['1 Month','0.1 credit'],['3 Month','0.25 credit'],['6 Month','0.5 credit'],['1 Year','1 credit']];
function table(rows,a,b){return `<div class="orbit-table"><table><thead><tr><th>${a}</th><th>${b}</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td></tr>`).join('')}</tbody></table></div>`}
function resellerSection(){return `<section class="unified-reseller section-shell"><div class="section-label"><span>04</span><i></i><b>RESELLER PROGRAM</b></div><div class="unified-heading"><h2>Build your business with Orbit IPTV.</h2><p>Choose a credit package, create customer subscriptions and manage them from your reseller panel.</p></div><div class="unified-tables"><article><h3>Credit packages</h3>${table(resellerCredits,'Credits','Price')}</article><article><h3>Subscription credit cost</h3>${table(subscriptions,'IPTV subscription duration','Credit cost')}</article></div><div class="unified-actions"><a class="button button-primary" data-wa="reseller" href="#">Join on WhatsApp →</a><a class="button button-outline" href="reseller.html">Reseller details →</a></div></section>`}
function installationSection(){return `<section class="unified-install section-shell"><div><div class="section-label"><span>05</span><i></i><b>INSTALLATION</b></div><h2>Setup for every screen.</h2><p>Follow the complete OrbitTV guide for Smart TV, Android, Firestick, iPhone, computers and other supported devices.</p><a class="button button-primary" href="${install}" target="_blank" rel="noopener">Open Installation Guide →</a></div><img src="assets/orbit-logo.png" alt="OrbitTV installation guide"></section>`}
function orbitServiceUpgrade(){
 if(document.body.dataset.page!=='service'||new URLSearchParams(location.search).get('view')!=='orbit')return;
 const app=document.querySelector('#serviceApp');if(!app||!app.querySelector('.price-grid')||app.dataset.orbitUnified)return;
 app.dataset.orbitUnified='true';
 const hero=app.querySelector('.page-hero');
 if(hero){hero.classList.add('orbit-plus-hero');const copy=hero.querySelector(':scope > div');if(copy){copy.querySelector('.eyebrow').innerHTML='<i></i>OrbitTV Plus';copy.querySelector('h1').innerHTML='Sva vaša zabava<br><em>na jednom mjestu.</em>';copy.querySelector('p').textContent='TV kanali, filmovi i serije na uređajima koje već koristite. Brza podrška preko Telegrama i WhatsAppa.'}const art=hero.querySelector('.page-service-art');if(art)art.innerHTML='<img src="assets/orbit-logo.png" alt="OrbitTV Plus">'}
 const prices=app.querySelector('.content-section');
 const extra=document.createElement('div');extra.className='orbit-service-extra';extra.innerHTML=`<section class="orbit-benefits section-shell"><div class="content-title"><small>SVE NA JEDNOM MJESTU</small><h2>OrbitTV na svakom ekranu.</h2><p>Veliki izbor televizijskih kanala, filmova i serija uz pomoć pri aktivaciji i instalaciji.</p></div><div class="orbit-feature-cards"><article><span>01</span><h3>TV kanali</h3><p>Domaće i međunarodne kategorije organizovane za lako pronalaženje.</p></article><article><span>02</span><h3>Filmovi i serije</h3><p>Zabava za cijelu porodicu na uređajima koje već koristite.</p></article><article><span>03</span><h3>Direktna podrška</h3><p>Pomoć pri testu, aktivaciji, instalaciji i korištenju usluge.</p></article></div></section><section class="orbit-channel-promo section-shell"><div><small>AKTUELNI KATALOG</small><h2>OrbitTV lista kanala</h2><p>Pretražite kategorije, države i kanale u našoj kompletnoj listi.</p><a class="button button-primary" href="channel-list/">Pregledaj sve kanale →</a></div><img src="assets/orbit-logo.png" alt="OrbitTV lista kanala"></section>${resellerSection()}<section class="orbit-faq section-shell"><div class="content-title"><small>ČESTA PITANJA</small><h2>Kako vam možemo pomoći?</h2></div><div class="orbit-faq-list"><details><summary>Kako mogu dobiti besplatni test?</summary><p>Pošaljite nam poruku preko WhatsAppa ili Telegrama. OrbitTV probni račun traje 24 sata.</p></details><details><summary>Gdje mogu provjeriti listu kanala?</summary><p>Otvorite kompletnu listu kanala i pretražite željenu državu, kategoriju ili kanal.</p></details><details><summary>Kako instaliram OrbitTV?</summary><p>Otvorite naš Installation Guide za Smart TV, Android, Firestick, iPhone i računar.</p></details><details><summary>Kako mogu postati reseller?</summary><p>Odaberite paket kredita i javite nam se za pristup reseller panelu.</p></details></div></section><section class="orbit-contact section-shell"><small>ORBITTV PODRŠKA</small><h2>📲 Kontaktirajte nas danas!</h2><p>Za ponudu, test, aktivaciju, reseller paket ili tehničku pomoć javite nam se direktno.</p><div><a class="button button-primary" target="_blank" rel="noopener" href="https://t.me/dzekcano72">Telegram · @dzekcano72</a><a class="button button-outline" target="_blank" rel="noopener" href="https://wa.me/38669843976">WhatsApp · +386 69 843 976</a></div></section>`;
 if(prices)prices.after(extra);
}
function home(){const main=document.querySelector('main');if(!main)return;document.querySelector('.reseller-banner')?.remove();const payment=document.querySelector('#payments');const wrap=document.createElement('div');wrap.innerHTML=resellerSection()+installationSection();while(wrap.firstChild)main.insertBefore(wrap.firstChild,payment||null)}
function reseller(){const content=document.querySelector('.content-section');if(!content)return;content.innerHTML=`<div class="content-title"><small>CREDITS + PANEL</small><h2>OrbitTV Reseller Program</h2><p>Create and manage subscriptions for your customers.</p></div><div class="unified-tables"><article><h3>Credit packages</h3>${table(resellerCredits,'Credits','Price in EUR')}</article><article><h3>IPTV account pricing</h3>${table(subscriptions,'IPTV subscription duration','Credit cost')}</article></div><div class="unified-actions"><a class="button button-primary" href="https://wa.me/38669843976?text=${encodeURIComponent('Hello, I want to become an OrbitTV reseller. Please send me reseller panel information.')}" target="_blank" rel="noopener">Join on WhatsApp →</a></div>`}
function navigation(){document.querySelectorAll('.desktop-nav a, footer a, .page-actions a').forEach(a=>{const t=a.textContent.trim().toLowerCase();if(['installation','instalacija','namestitev','installazione'].includes(t)){a.href=install;a.target='_blank';a.rel='noopener'}if(t==='login'||t==='log in'||t==='sign up')a.remove()})}
function channelPage(){if(!location.pathname.includes('channel-list'))return;document.querySelectorAll('[data-topic]').forEach(a=>{const t=(a.dataset.topic||'').toLowerCase();if(['blog','system status','legal information'].includes(t))a.remove()});const account=[...document.querySelectorAll('footer section')].find(s=>/account/i.test(s.textContent));account?.remove();}
function bind(){document.querySelectorAll('[data-wa="reseller"]').forEach(a=>a.href='https://wa.me/38669843976?text='+encodeURIComponent('Hello, I want to become an OrbitTV reseller. Please send me reseller panel information.'))}
function init(){navigation();channelPage();if(document.body.dataset.page==='home')home();if(location.pathname.endsWith('/reseller.html')||new URLSearchParams(location.search).get('view')==='reseller')reseller();orbitServiceUpgrade();bind()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
let refreshQueued=false;
new MutationObserver(()=>{if(refreshQueued)return;refreshQueued=true;requestAnimationFrame(()=>{refreshQueued=false;navigation();orbitServiceUpgrade();bind()})}).observe(document.documentElement,{childList:true,subtree:true});
})();

